package com.mycompany.proyectoormjoelcoutolugo.vistasActualizar;

import com.mycompany.proyectoormjoelcoutolugo.entidades.Piloto;
import com.mycompany.proyectoormjoelcoutolugo.utils.HibernateUtil;
import com.mycompany.proyectoormjoelcoutolugo.utils.PilotoDAO;
import static com.mycompany.proyectoormjoelcoutolugo.vistasActualizar.ActualizarAvionView.esNoNuloNoVacio;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Iproy
 */
public class ActualizarPilotoView extends javax.swing.JFrame {

    HibernateUtil hUtil = new HibernateUtil();
    PilotoDAO pilotoDAO;
    Piloto pilotoActulizar;

    public ActualizarPilotoView() {
        initComponents();
        pilotoDAO = new PilotoDAO(hUtil.getSessionFactory());
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idPilotoTextField = new javax.swing.JTextField();
        buscasPilotoButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        codigoPilotoTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombrePilotoTextField = new javax.swing.JTextField();
        horasVueloTextField = new javax.swing.JTextField();
        actualizarPilotoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Actualizar Piloto");

        jLabel2.setText("Id del piloto");

        buscasPilotoButton.setText("Buscar piloto");
        buscasPilotoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscasPilotoButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Codigo del piloto");

        codigoPilotoTextField.setEnabled(false);

        jLabel4.setText("Nombre");

        jLabel5.setText("Horas de vuelo");

        nombrePilotoTextField.setEnabled(false);

        horasVueloTextField.setEnabled(false);

        actualizarPilotoButton.setText("Actualizar");
        actualizarPilotoButton.setEnabled(false);
        actualizarPilotoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarPilotoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(idPilotoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buscasPilotoButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(63, 63, 63))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(codigoPilotoTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                    .addComponent(nombrePilotoTextField)
                                    .addComponent(horasVueloTextField, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(actualizarPilotoButton)
                        .addGap(45, 45, 45))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idPilotoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscasPilotoButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoPilotoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombrePilotoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(horasVueloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(actualizarPilotoButton)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscasPilotoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscasPilotoButtonActionPerformed
        String idPilotoActualizar = idPilotoTextField.getText();

        if (!esNoNuloNoVacio(idPilotoActualizar)) {
            mostrarMensaje("EL ID NO PUEDE ESTAR VACIO");
        } else if (!esNumero(idPilotoActualizar)) {
            mostrarMensaje("EL ID NO PUEDE TENER LETRAS");
        } else {

            pilotoActulizar = pilotoDAO.obtenerPilotoPorId(Long.parseLong(idPilotoActualizar));

            if (pilotoActulizar == null) {
                mostrarMensaje("NO SE HA ECONTRADO NINGUN PILOTO CON ESE ID");
            } else {
                codigoPilotoTextField.setEnabled(true);
                nombrePilotoTextField.setEnabled(true);
                actualizarPilotoButton.setEnabled(true);
                horasVueloTextField.setEnabled(true);
                buscasPilotoButton.setEnabled(false);

                codigoPilotoTextField.setText(pilotoActulizar.getCodigo());
                nombrePilotoTextField.setText(pilotoActulizar.getNombre());
                horasVueloTextField.setText(String.valueOf(pilotoActulizar.getHorasDeVuelo()));

            }

        }
    }//GEN-LAST:event_buscasPilotoButtonActionPerformed

    private void actualizarPilotoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarPilotoButtonActionPerformed
        String codigoPiloto = codigoPilotoTextField.getText();
        String nombrePiloto = nombrePilotoTextField.getText();
        String horasDeVuelo = horasVueloTextField.getText();
        
        if(!esNoNuloNoVacio(codigoPiloto)){
            mostrarMensaje("EL CODIGO NO PUEDE ESTAR VACIO");
        }else if (!esNoNuloNoVacio(nombrePiloto)){
            mostrarMensaje("EL NOMBRE NO PUEDE ESTAR VACIO");
        }else if (!esNumero(horasDeVuelo)){
            mostrarMensaje("LAS HORAS DE VUELO TIENEN QUE SER UN NUMERO");
        }else{
            pilotoActulizar.setCodigo(codigoPiloto);
            pilotoActulizar.setNombre(nombrePiloto);
            pilotoActulizar.setHorasDeVuelo(Integer.parseInt(horasDeVuelo));
            pilotoDAO.actualizarPiloto(pilotoActulizar);
            mostrarMensaje("PILOTO ACTUALIZADO");
            this.setVisible(false);
        }
    }//GEN-LAST:event_actualizarPilotoButtonActionPerformed

    public boolean esNumero(String cadena) {
        try {
            // Intenta convertir la cadena a un número
            Long.parseLong(cadena);
            return true;
        } catch (NumberFormatException e) {
            // Si ocurre una excepción, la cadena no es un número
            return false;
        }
    }

    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje);
    }

    public static boolean esNoNuloNoVacio(String cadena) {
        return cadena != null && !cadena.isEmpty();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarPilotoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarPilotoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarPilotoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarPilotoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarPilotoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarPilotoButton;
    private javax.swing.JButton buscasPilotoButton;
    private javax.swing.JTextField codigoPilotoTextField;
    private javax.swing.JTextField horasVueloTextField;
    private javax.swing.JTextField idPilotoTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nombrePilotoTextField;
    // End of variables declaration//GEN-END:variables
}
